### ISSUE TITLE
aioredis (version >=2.0) has no attribute create_redis

### ISSUE THREAD

**Issue by guillheu** [aleph-im/aleph-vm#191]
**Describe the bug**
When testing the vm supervisor natively (not in a docker container), the vm fails to boot due to the following error :
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/root/aleph-vm/guest_api/__main__.py", line 128, in put_in_cache
    redis: aioredis.Redis = await get_redis()
  File "/root/aleph-vm/guest_api/__main__.py", line 24, in get_redis
    _redis = await aioredis.create_redis(address=address)
AttributeError: module 'aioredis' has no attribute 'create_redis'
```
After a quick search, it seems the `create_redis` method was removed from `aioredis` version 2.0 ([source](https://stackoverflow.com/questions/68901119/module-aioredis-has-no-attribute-create-redis))
I suggest forcing the use of `aioredis 1.3` in the dependencies documentation.

**To Reproduce**
1: clone the aleph-vm repo
2: follow the steps described in [/tutorials/TESTING.md](https://github.com/aleph-im/aleph-vm/blob/main/tutorials/TESTING.md) and install the latest version of `aioredis` with pip
3: start the vm supervisor natively (`python3 -m ...` command)
4: access http://localhost:4020

**Expected behavior**
The micro vm should successfully start.

**Desktop (please complete the following information):**
 - OS: arch linux 5.17.9
 - Browser : Brave

**Comment by guillheu** [comment]
Actually, my suggested solution of using aioredis 1.3 will not work.
aioredis 1.3 uses the `asyncio.wait_for` method, for which the `loop` argument has been deprecated from python since 3.8, and removed in 3.10. This makes aioredis 1.3 incompatible with python 3.10.

However, at first glance seems to work with `aioredis 1.3.1`

**Comment by guillheu** [comment]
I seem to be hitting another issue with aioredis (or aiohttp, not sure)
essentially, in `guest_api/__main.py` line 24, the address set (`redis://localhost`) will resolve to both ipv6 and ipv4. My internal dns will first resolve it as ipv6. Of course, the redis server only runs on ipv4.
Normally, aioredis should first try connecting to the ipv6 resolved address, then the ipv4.
However, it instead seems to stop if it cant connect on the first attempt ; it wont try the next dns resolution to ipv4. this makes the connection to the VM fail even though it's running just fine.
related post : https://github.com/aio-libs/aiohttp/issues/2402

This might be resolved by updating the guest api to work with the latest versions of aioredis, aiohttp and python.

**Comment by hoh** [comment]
PS: I am using Arch Linux myself, I just run everything inside containers or Firecracker virtual machines 😉.
